name: Deploy infrastructure

on:
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set permissions for scripts
        run: chmod +x ./scripts/cd/*.sh

      - name: Decrypt Kubeconfig
        run: |
          openssl enc -aes-256-cbc -d -in ./secrets/kubeconfig.enc -out kubeconfig -pass pass:${{ secrets.DECRYPTION_KEY }}

      - name: Set Kubeconfig Environment Variable
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig" >> $GITHUB_ENV

      - name: Validate Kubeconfig
        run: kubectl config view --kubeconfig=$GITHUB_WORKSPACE/kubeconfig

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          kubeconfig: ${{ github.workspace }}/kubeconfig

      - name: Deploy MongoDB
        run: kubectl apply -f ./scripts/cd/mongodb.yaml

      - name: Deploy RabbitMQ
        run: kubectl apply -f ./scripts/cd/rabbit.yaml
