# 
# GitHub Actions workflow.
#
# Deploys RabbitMQ and MongoDB database.
#

name: Deploy infrastructure

on:
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Decode and set up KUBE_CONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG_ZIP }}" | base64 -d > kubeconfig.zip
          unzip kubeconfig.zip -d ~/.kube
        shell: bash

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          kubeconfig: ~/.kube/config

      - name: Deploy MongoDB
        run: kubectl apply -f ./scripts/cd/mongodb.yaml

      - name: Deploy Rabbit
        run: kubectl apply -f ./scripts/cd/rabbit.yaml
