name: Deploy video-upload

on:
  push: 
    branches:
      - main
    paths:
      - video-upload/**

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      NAME: video-upload
      DIRECTORY: video-upload

    steps:
      
      - uses: actions/checkout@v3

      - name: Build
        run: ./scripts/cd/build-image.sh

      - name: Publish
        run: ./scripts/cd/push-image.sh

      - name: Reconstruct Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_PART_1 }}" > kubeconfig_base64
          echo "${{ secrets.KUBE_CONFIG_PART_2 }}" >> kubeconfig_base64
          echo "${{ secrets.KUBE_CONFIG_PART_3 }}" >> kubeconfig_base64
          echo "${{ secrets.KUBE_CONFIG_PART_4 }}" >> kubeconfig_base64
          cat kubeconfig_base64 | base64 -d > kubeconfig.enc

      - name: Decrypt Kubeconfig
        run: |
          openssl enc -aes-256-cbc -d -in kubeconfig.enc -out kubeconfig -pass pass:${{ secrets.DECRYPTION_KEY }}

      - name: Set Kubeconfig Environment Variable
        run: export KUBECONFIG=$GITHUB
