# 
# GitHub Actions workflow.
#
# Automatically deploys the Node.js microservice to Kubernetes on push to the main branch.
#

name: Deploy video-upload

on:
  push: 
    branches:
      - main
    paths:
      - video-upload/**

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      NAME: video-upload
      DIRECTORY: video-upload

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: ./scripts/cd/build-image.sh

      - name: Publish
        run: ./scripts/cd/push-image.sh

      - name: Decode and set up KUBE_CONFIG
        run: |
          echo "${{ secrets.KUBE_CONFIG_ZIP }}" | base64 -d > kubeconfig.zip
          unzip kubeconfig.zip -d ~/.kube
        shell: bash

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
          kubeconfig: ~/.kube/config

      - name: Deploy
        run: ./scripts/cd/deploy.sh
