name: Deploy video-upload

on:
  push: 
    branches:
      - main
    paths:
      - video-upload/**

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW }}
      NAME: video-upload
      DIRECTORY: video-upload

    steps:
      - uses: actions/checkout@v3

      - name: Set permissions for scripts
        run: chmod +x ./scripts/cd/*.sh

      - name: Build
        run: ./scripts/cd/build-image.sh

      - name: Publish
        run: ./scripts/cd/push-image.sh

      - name: Decrypt Kubeconfig
        run: |
          openssl enc -aes-256-cbc -d -in ./secrets/kubeconfig.enc -out kubeconfig -pass pass:${{ secrets.DECRYPTION_KEY }}

      - name: Set Kubeconfig Environment Variable
        run: echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig
